pull_request_rules:
  - name: backport patches to v0.5.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.5.x
    actions:
      backport:
        branches:
          - v0.5.x
  - name: backport patches to v0.6.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.6.x
    actions:
      backport:
        branches:
          - v0.6.x
