name: github pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.21"

      - name: Build book
        run: mdbook build specs

      - name: Deploy main
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./specs/book
          # keep_files is to prevent PR preview files from being overwritten.
          # If we need to overwrite such files, trigger this workflow manually.
          keep_files: ${{ github.event_name != 'workflow_dispatch' }}

      - name: Deploy PR preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./specs/book
