name: govulncheck
# Runs https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck to proactively
# check for vulnerabilities.
#
# Run `make vulncheck` from the root of the repo to run this workflow locally.
on:
  pull_request:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: make govulncheck
        run: make govulncheck
