name: govulncheck
# Runs https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck to proactively
# check for vulnerabilities.
#
# Run `make vulncheck` from the root of the repo to run this workflow locally.
on:
  pull_request:

env:
  GO_VERSION: '1.22.0'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
      - name: make govulncheck
        run: make govulncheck
