name: Check Markdown links
on: 
  # schedule: 
  #   - cron: '* */24 * * *'
  workflow_dispatch:
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          folder-path: "docs"
