name: nightly
on:
  schedule:
    # runs every day at 6am UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test-e2e:
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
