name: test-interchain
on:
  workflow_call:

env:
  DOCKER_IMAGE: celestiaorg/celestia-app
  ARTIFACT_NAME: celestia-app-docker-image
  ARTIFACT_PATH: celestia-app-docker-image.tar

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build celestia-app Docker image
        run: make build-docker

      - name: Save Docker image as artifact
        run: docker image save -o ${{ env.ARTIFACT_PATH }} ${{ env.DOCKER_IMAGE }}

      - name: Publish Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}


  test-interchain:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Load Docker image
        run: docker image load -i ${{ env.ARTIFACT_PATH }}

      - name: Print Docker images
        run: docker images

      - name: Run interchain tests
        run: make test-interchain
